# Generated by Django 2.1.7 on 2019-03-15 19:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_name', models.CharField(default='', max_length=50, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(default='', max_length=1024)),
                ('team_image', models.ImageField(default='default.jpg', upload_to='team_pics')),
                ('created_on', models.DateField(default=datetime.datetime(2019, 3, 15, 19, 4, 9, 123885, tzinfo=utc))),
                ('team_lead', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_lead_key', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_invited', models.BooleanField(default=False)),
                ('current_team_lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
