# Generated by Django 2.1.7 on 2019-03-16 09:04

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammanagement',
            name='current_team_lead',
        ),
        migrations.RemoveField(
            model_name='teammanagement',
            name='users',
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2019, 3, 16, 9, 4, 31, 204424, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='TeamManagement',
        ),
    ]
