# Generated by Django 2.1.7 on 2019-03-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20190314_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='member_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='team',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_members',
        ),
        migrations.AddField(
            model_name='team',
            name='team_members',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
