# Generated by Django 2.1.7 on 2019-03-16 09:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20190316_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2019, 3, 16, 9, 11, 56, 444862, tzinfo=utc)),
        ),
    ]
