# Generated by Django 2.1.7 on 2019-03-15 11:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0012_auto_20190315_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2019, 3, 15, 11, 28, 6, 18335, tzinfo=utc)),
        ),
    ]
