# Generated by Django 2.1.7 on 2019-03-15 12:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0014_auto_20190315_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='team_c',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='user_c',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_members',
        ),
        migrations.AlterField(
            model_name='team',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2019, 3, 15, 12, 26, 40, 931408, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
