# Generated by Django 2.1.7 on 2019-03-15 15:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0015_auto_20190315_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamlead',
            name='current_user',
        ),
        migrations.AddField(
            model_name='teamlead',
            name='current_team_lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2019, 3, 15, 15, 36, 25, 226665, tzinfo=utc)),
        ),
    ]
