# Generated by Django 2.1.7 on 2019-03-15 15:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0016_auto_20190315_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2019, 3, 15, 15, 36, 53, 955884, tzinfo=utc)),
        ),
    ]
