# Generated by Django 2.1.7 on 2019-03-15 15:41

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0017_auto_20190315_1536'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamLead',
            new_name='TeamManagement',
        ),
        migrations.AlterField(
            model_name='team',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2019, 3, 15, 15, 41, 1, 442743, tzinfo=utc)),
        ),
    ]
