# Generated by Django 2.1.7 on 2019-03-15 16:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0018_auto_20190315_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammanagement',
            name='is_invited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2019, 3, 15, 16, 15, 20, 615038, tzinfo=utc)),
        ),
    ]
