# Generated by Django 2.1.7 on 2019-03-14 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('bio', models.CharField(blank=True, default='NA', max_length=500)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='', max_length=6)),
                ('skills', multiselectfield.db.fields.MultiSelectField(choices=[('frontend', 'Front End'), ('backend', 'Back End'), ('fullstack_web', 'FullStack Web'), ('machine_learning', 'Machine Learning'), ('data_science', 'Data Science'), ('networking', 'Networking'), ('mobile_app_develop', 'Mobile App Development')], default='', max_length=3000)),
                ('city', models.CharField(choices=[('ahmedabad', 'Ahmedabad'), ('vadodara', 'Vadodara'), ('surat', 'Surat'), ('rajkot', 'Rajkot'), ('other', 'Other')], default='', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
