# Generated by Django 2.1.7 on 2019-03-16 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20190316_0905'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='team_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='teams.Team'),
        ),
    ]
