# Generated by Django 2.1.7 on 2019-03-16 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='team_name',
        ),
    ]
