# Generated by Django 2.1.7 on 2019-03-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_no',
            field=models.CharField(blank=True, default='0', max_length=15),
        ),
    ]
