# Generated by Django 2.1.7 on 2019-03-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190314_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='qualification',
            field=models.CharField(choices=[('bachelors', 'Bachelors'), ('masters', 'Masters'), ('phd', 'PhD'), ('postdoc', 'PostDoc'), ('other', 'Other')], default='bachelors', max_length=30),
        ),
    ]
