# Generated by Django 2.1.7 on 2019-03-14 18:31

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='qualification',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('bachelors', 'Bachelors'), ('masters', 'Masters'), ('phd', 'PhD'), ('postdoc', 'PostDoc'), ('other', 'Other')], default='bachelors', max_length=30),
        ),
    ]
