# Generated by Django 2.1.7 on 2019-03-16 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190316_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='team_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_name_profile', to='teams.Team'),
        ),
    ]
