# Generated by Django 2.1.7 on 2019-03-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190316_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='file',
            field=models.FileField(null=True, upload_to='profile_pics'),
        ),
    ]
