# Generated by Django 2.1.7 on 2019-03-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='file',
            field=models.FileField(null=True, upload_to='documents'),
        ),
    ]
